FROM openjdk:17-jdk-slim

WORKDIR /app

COPY gradlew gradlew.bat build.gradle settings.gradle /app/
COPY gradle /app/gradle
COPY src /app/src

RUN ./gradlew build -x test

EXPOSE 8080

CMD ["java", "-jar", "build/libs/webshop-0.0.1-SNAPSHOT.jar"]
